spring:
  application:
    name: GateWay-Api
  cloud:
    gateway:
      routes:
      - id: Welcome-Api
        uri: lb://WELCOME-API
        predicates:
        - Path=/api/wel/**
      - id: Greet-Api
        uri: lb://Greet-Api
        predicates:
        - Path=/api/gr/**
      - id: AuthService_Api
        uri: http://localhost:7071
        predicates:
        - Path=/auth/**
server:
  port: 3333
eureka:
  client:
    register-with-eureka: true
